/**
 * generated by Xtext 2.13.0
 */
package com.visteon.onoff.coom;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component On Off Manifest</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.visteon.onoff.coom.ComponentOnOffManifest#getName <em>Name</em>}</li>
 *   <li>{@link com.visteon.onoff.coom.ComponentOnOffManifest#getVersion <em>Version</em>}</li>
 *   <li>{@link com.visteon.onoff.coom.ComponentOnOffManifest#getStates <em>States</em>}</li>
 *   <li>{@link com.visteon.onoff.coom.ComponentOnOffManifest#getTransitions <em>Transitions</em>}</li>
 * </ul>
 *
 * @see com.visteon.onoff.coom.CoomPackage#getComponentOnOffManifest()
 * @model
 * @generated
 */
public interface ComponentOnOffManifest extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.visteon.onoff.coom.CoomPackage#getComponentOnOffManifest_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.visteon.onoff.coom.ComponentOnOffManifest#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Version</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' containment reference.
   * @see #setVersion(Version)
   * @see com.visteon.onoff.coom.CoomPackage#getComponentOnOffManifest_Version()
   * @model containment="true"
   * @generated
   */
  Version getVersion();

  /**
   * Sets the value of the '{@link com.visteon.onoff.coom.ComponentOnOffManifest#getVersion <em>Version</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' containment reference.
   * @see #getVersion()
   * @generated
   */
  void setVersion(Version value);

  /**
   * Returns the value of the '<em><b>States</b></em>' containment reference list.
   * The list contents are of type {@link com.visteon.onoff.coom.State}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>States</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>States</em>' containment reference list.
   * @see com.visteon.onoff.coom.CoomPackage#getComponentOnOffManifest_States()
   * @model containment="true"
   * @generated
   */
  EList<State> getStates();

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link com.visteon.onoff.coom.Transition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Transitions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see com.visteon.onoff.coom.CoomPackage#getComponentOnOffManifest_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<Transition> getTransitions();

} // ComponentOnOffManifest
