/*
 * generated by Xtext 2.13.0
 */
package com.visteon.onoff.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStatesScopeProvider extends DelegatingScopeProvider {
}
