/*
 * generated by Xtext 2.13.0
 */
package com.visteon.onoff.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StatesAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/visteon/onoff/parser/antlr/internal/InternalStates.tokens");
	}
}
