/*
 * generated by Xtext 2.13.0
 */
package com.visteon.onoff.ui.tests;

import com.google.inject.Injector;
import com.visteon.onoff.coom.ui.internal.CoomActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CoomUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CoomActivator.getInstance().getInjector("com.visteon.onoff.Coom");
	}

}
