/*
 * generated by Xtext 2.13.0
 */
package com.visteon.onoff


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StatesStandaloneSetup extends StatesStandaloneSetupGenerated {

	def static void doSetup() {
		new StatesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
