/**
 * generated by Xtext 2.13.0
 */
package com.visteon.onoff.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.visteon.onoff.StatesRuntimeModule;
import com.visteon.onoff.StatesStandaloneSetup;
import com.visteon.onoff.ide.StatesIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class StatesIdeSetup extends StatesStandaloneSetup {
  @Override
  public Injector createInjector() {
    StatesRuntimeModule _statesRuntimeModule = new StatesRuntimeModule();
    StatesIdeModule _statesIdeModule = new StatesIdeModule();
    return Guice.createInjector(Modules2.mixin(_statesRuntimeModule, _statesIdeModule));
  }
}
