/*
 * generated by Xtext 2.13.0
 */
package com.visteon.onoff.ui;

import com.google.inject.Injector;
import com.visteon.onoff.coom.ui.internal.CoomActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CoomExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CoomActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CoomActivator activator = CoomActivator.getInstance();
		return activator != null ? activator.getInjector(CoomActivator.COM_VISTEON_ONOFF_COOM) : null;
	}

}
