/*
 * generated by Xtext 2.13.0
 */
package com.visteon.onoff.validation

import org.eclipse.xtext.EcoreUtil2
import org.eclipse.xtext.validation.Check
import com.visteon.onoff.coom.CoomPackage

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class CoomValidator extends AbstractCoomValidator {

//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					CoomPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	@Check
	def checkForMultipleInitialStates(com.visteon.onoff.coom.State state) {
		if (state.isInitial) {
			if (EcoreUtil2.getSiblingsOfType(state, com.visteon.onoff.coom.State).filter[isInitial].size > 0) {
				error('A component cannot have multiple start States', CoomPackage.Literals.STATE__INITIAL)
			}
		}
	}

}
