/**
 * generated by Xtext 2.13.0
 */
package com.visteon.onoff.states;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node State Diagram</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.visteon.onoff.states.NodeStateDiagram#getGEdgeWeight <em>GEdge Weight</em>}</li>
 *   <li>{@link com.visteon.onoff.states.NodeStateDiagram#getGTransitionTimeoutInMilliseconds <em>GTransition Timeout In Milliseconds</em>}</li>
 *   <li>{@link com.visteon.onoff.states.NodeStateDiagram#getNodeStates <em>Node States</em>}</li>
 *   <li>{@link com.visteon.onoff.states.NodeStateDiagram#getNodeTransitions <em>Node Transitions</em>}</li>
 * </ul>
 *
 * @see com.visteon.onoff.states.StatesPackage#getNodeStateDiagram()
 * @model
 * @generated
 */
public interface NodeStateDiagram extends EObject
{
  /**
   * Returns the value of the '<em><b>GEdge Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>GEdge Weight</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>GEdge Weight</em>' attribute.
   * @see #setGEdgeWeight(int)
   * @see com.visteon.onoff.states.StatesPackage#getNodeStateDiagram_GEdgeWeight()
   * @model
   * @generated
   */
  int getGEdgeWeight();

  /**
   * Sets the value of the '{@link com.visteon.onoff.states.NodeStateDiagram#getGEdgeWeight <em>GEdge Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>GEdge Weight</em>' attribute.
   * @see #getGEdgeWeight()
   * @generated
   */
  void setGEdgeWeight(int value);

  /**
   * Returns the value of the '<em><b>GTransition Timeout In Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>GTransition Timeout In Milliseconds</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>GTransition Timeout In Milliseconds</em>' attribute.
   * @see #setGTransitionTimeoutInMilliseconds(int)
   * @see com.visteon.onoff.states.StatesPackage#getNodeStateDiagram_GTransitionTimeoutInMilliseconds()
   * @model
   * @generated
   */
  int getGTransitionTimeoutInMilliseconds();

  /**
   * Sets the value of the '{@link com.visteon.onoff.states.NodeStateDiagram#getGTransitionTimeoutInMilliseconds <em>GTransition Timeout In Milliseconds</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>GTransition Timeout In Milliseconds</em>' attribute.
   * @see #getGTransitionTimeoutInMilliseconds()
   * @generated
   */
  void setGTransitionTimeoutInMilliseconds(int value);

  /**
   * Returns the value of the '<em><b>Node States</b></em>' containment reference list.
   * The list contents are of type {@link com.visteon.onoff.states.NodeState}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node States</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node States</em>' containment reference list.
   * @see com.visteon.onoff.states.StatesPackage#getNodeStateDiagram_NodeStates()
   * @model containment="true"
   * @generated
   */
  EList<NodeState> getNodeStates();

  /**
   * Returns the value of the '<em><b>Node Transitions</b></em>' containment reference list.
   * The list contents are of type {@link com.visteon.onoff.states.NodeTransition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node Transitions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Transitions</em>' containment reference list.
   * @see com.visteon.onoff.states.StatesPackage#getNodeStateDiagram_NodeTransitions()
   * @model containment="true"
   * @generated
   */
  EList<NodeTransition> getNodeTransitions();

} // NodeStateDiagram
