/*
 * generated by Xtext 2.13.0
 */
package com.visteon.onoff.ui.tests;

import com.google.inject.Injector;
import com.visteon.onoff.states.ui.internal.StatesActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class StatesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StatesActivator.getInstance().getInjector("com.visteon.onoff.States");
	}

}
